# -*- coding: utf-8 -*-
"""DSA mock_test_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qOS6wRz8ACgh7n1d4F1L5dMn4MkvMOrM
"""

class Stack:
    def __init__(self):
        self.stack = []

    def push(self, item):
        self.stack.append(item)

    def pop(self):
        if not self.isEmpty():
            return self.stack.pop()
        else:
            raise IndexError("Stack is empty.")

    def isEmpty(self):
        return len(self.stack) == 0

stack = Stack()
print(stack.isEmpty())  # True

stack.push(10)
stack.push(20)
stack.push(30)
print(stack.isEmpty())  # False

print(stack.pop())
print(stack.pop())
print(stack.pop())
print(stack.isEmpty())

class Queue:
    def __init__(self):
        self.queue = []

    def enqueue(self, item):
        self.queue.append(item)

    def dequeue(self):
        if not self.isEmpty():
            return self.queue.pop(0)
        else:
            raise IndexError("Queue is empty.")

    def isEmpty(self):
        return len(self.queue) == 0

queue = Queue()
print(queue.isEmpty())

queue.enqueue(10)
queue.enqueue(20)
queue.enqueue(30)
print(queue.isEmpty())

print(queue.dequeue())
print(queue.dequeue())
print(queue.dequeue())
print(queue.isEmpty())